const { ObjectID } = require('bson')
const { object } = require('joi')

const swaggerAutogen = require('swagger-autogen')()

const outputFile = './swagger_output.json'
const endpointsFiles = ['./index.js']


const doc = {
        
  "swagger": "2.0",
  "info": {
    "version": "1.0.0",
    "title": "REST API",
    "description": "Documentation automatically generated by the <b>swagger-autogen</b> module."
  },
  "host": "https://vicara-storage-drive.herokuapp.com",
  "basePath": "/",
  "tags": [
	  {
		"name": "User",
		"description": "Endpoints"
    }
  ],
  "schemes": [
    'http', 'https'
  ],
  "consumes": ['application/json'],
  "produces": ['application/json'],
	"definitions": {
      User: {
        $name: "Rahul Senguttuvan",
        $email: "testEmail@gmail.com",
        $password: "******"
      },
      File: {
        $document_id: 123456787,
        $description: "testEmail@gmail.com",
        $fileLink: "******",
        $s3_key: "213123",
        $favourite: true,
        viewers: [
          {
            ref: ObjectID,
          }
        ],
        users: [
          {
            ref: ObjectID,
          }
        ],
        creator: ObjectID,
        parentFolder: "nameOfFolder",
        isIndependant: true,
      },
      Folder: {
        $folder_id: 123456787,
        $Name: "nameofFolder",
        $favourite: true,
        $s3_key: "213123",
        $favourite: true,
        users: [
          {
            ref: ObjectID,
          }
        ],
        files: [
          {
            ref: ObjectID,
          }
        ],
        folders: [
          {
            ref: ObjectID,
          }
        ],
        creator: ObjectID,
        parentFolder: "nameOfFolder",
        isIndependant: true,
      }
  }

}

swaggerAutogen(outputFile, endpointsFiles,doc).then(() => {
    require('./index.js')
})