const swaggerAutogen = require('swagger-autogen')()

const outputFile = './swagger_output.json'
const endpointsFiles = ['./index.js']


const doc = {
        
  "swagger": "2.0",
  "info": {
    "version": "1.0.0",
    "title": "REST API",
    "description": "Documentation automatically generated by the <b>swagger-autogen</b> module."
  },
  "host": "localhost:3000",
  "basePath": "/",
  "tags": [
	  {
		"name": "User",
		"description": "Endpoints"
    }
  ],
  "schemes": [
    "http"
  ],
  "consumes": [],
  "produces": [],
	"definitions": {
      User: {
        $name: "Rahul Senguttuvan",
        $email: "testEmail@gmail.com",
        $password: "******"
      }
  }

}

swaggerAutogen(outputFile, endpointsFiles,doc).then(() => {
    require('./index.js')
})